export const EVENTS_REPOSITORY = "EVENTS_REPOSITORY"
export const PARTICIPANTS_REPOSITORY = "PARTICIPANTS_REPOSITORY"
export const DATA_SOURCE = "DATA_SOURCE"
export const USERS_REPOSITORY = "USERS_REPOSITORY"